In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# load datasets
diabetes = pd.read_csv('/content/drive/MyDrive/Bimbing/Hyperparameter Tuning/diabetes.csv')
heart = pd.read_csv('/content/drive/MyDrive/Bimbing/Hyperparameter Tuning/heart_failure.csv')
live = pd.read_csv('/content/drive/MyDrive/Bimbing/Hyperparameter Tuning/fb_live.csv')

In [ ]:
diabetes.head()

   AGE  SEX   BMI     BP   S1     S2    S3   S4      S5  S6    Y
0   59    2  32.1  101.0  157   93.2  38.0  4.0  4.8598  87  151
1   48    1  21.6   87.0  183  103.2  70.0  3.0  3.8918  69   75
2   72    2  30.5   93.0  156   93.6  41.0  4.0  4.6728  85  141
3   24    1  25.3   84.0  198  131.4  40.0  5.0  4.8903  89  206
4   50    1  23.0  101.0  192  125.4  52.0  4.0  4.2905  80  135

In [ ]:
diabetes['Y']. value_counts()

Y
200    6
72     6
178    5
71     5
90     5
      ..
146    1
212    1
120    1
183    1
57     1
Name: count, Length: 214, dtype: int64

In [ ]:
# as always, first thing is to split the data
from sklearn.model_selection import train_test_split

X = diabetes.drop(columns='Y').to_numpy()
y = diabetes[['Y']].to_numpy()
y = y.reshape(len(y),) # sklearn's shape requirement

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [ ]:
# define ridge regression model
from sklearn.linear_model import Ridge

ridge_reg = Ridge(random_state=42)

In [ ]:
# tune lambda (denote as 'alpha' in sklearn)
# using GridSearchCV
from sklearn.model_selection import GridSearchCV

# hyperparameter values we want to tune
parameters = {
    'alpha': (0.000001,0.00001,0.0001,0.001,
              0.01, 0.1, 1, 5, 10, 20),
    'max_iter' : (700,800,900,1000, None),
    'copy_X': (True, False)
}

# the tuning
ridge_reg_gridcv = GridSearchCV(ridge_reg, parameters, cv=5,
                                scoring='neg_root_mean_squared_error')
ridge_reg_gridcv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=Ridge(random_state=42),
             param_grid={'alpha': (1e-06, 1e-05, 0.0001, 0.001, 0.01, 0.1, 1, 5,
                                   10, 20),
                         'copy_X': (True, False),
                         'max_iter': (700, 800, 900, 1000, None)},
             scoring='neg_root_mean_squared_error')

In [ ]:
# tune lambda (denote as 'alpha' in sklearn)
# using GridSearchCV
from sklearn.model_selection import GridSearchCV

# hyperparameter values we want to tune
parameters = {
    'alpha': (0.000001,0.00001,0.0001,0.001,
              0.01, 0.1, 1, 5, 10, 20),
    'max_iter' : (700,800,900,1000, None),
    'copy_X': (True, False)
}

# the tuning
scoring = {"neg_root_mean_squared_error": "neg_root_mean_squared_error", "r2": "r2"}

ridge_reg_gridcv = GridSearchCV(ridge_reg, parameters, cv=5,
                                scoring=scoring,
                                refit='neg_root_mean_squared_error',
                                n_jobs=-1,
                                )
ridge_reg_gridcv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=Ridge(random_state=42), n_jobs=-1,
             param_grid={'alpha': (1e-06, 1e-05, 0.0001, 0.001, 0.01, 0.1, 1, 5,
                                   10, 20),
                         'copy_X': (True, False),
                         'max_iter': (700, 800, 900, 1000, None)},
             refit='neg_root_mean_squared_error',
             scoring={'neg_root_mean_squared_error': 'neg_root_mean_squared_error',
                      'r2': 'r2'})

In [ ]:
# ridge_reg_000001 = Ridge(random_state=42, alpha=0.000001, max_iter = 700)
# ridge_reg_000001 = Ridge(random_state=42, alpha=0.000001, max_iter = 800)
# ridge_reg_000001 = Ridge(random_state=42, alpha=0.000001, max_iter = 900)
# ridge_reg_000001 = Ridge(random_state=42, alpha=0.000001, max_iter = 1000)


# ridge_reg_00001 = Ridge(random_state=42, alpha=0.00001, max_iter = 700)
# ridge_reg_00001 = Ridge(random_state=42, alpha=0.00001, max_iter = 800)

# ridge_reg_0001 = Ridge(random_state=42, alpha=0.0001 )

In [ ]:
# pd.DataFrame(ridge_reg_gridcv.cv_results_).head()

In [ ]:
# only show the most important columns
retain_cols = ['params','mean_test_score','rank_test_score']
cv_result = pd.DataFrame(ridge_reg_gridcv.cv_results_)
cv_result[retain_cols]

,params,mean_test_score,rank_test_score
0,"{'alpha': 1e-06, 'copy_X': True, 'max_iter': 700}",-55.972086,61
1,"{'alpha': 1e-06, 'copy_X': True, 'max_iter': 800}",-55.972086,61
2,"{'alpha': 1e-06, 'copy_X': True, 'max_iter': 900}",-55.972086,61
3,"{'alpha': 1e-06, 'copy_X': True, 'max_iter': 1...",-55.972086,61
4,"{'alpha': 1e-06, 'copy_X': True, 'max_iter': N...",-55.972086,61
...,...,...,...
95,"{'alpha': 20, 'copy_X': False, 'max_iter': 700}",-56.448279,91
96,"{'alpha': 20, 'copy_X': False, 'max_iter': 800}",-56.448279,91
97,"{'alpha': 20, 'copy_X': False, 'max_iter': 900}",-56.448279,91
98,"{'alpha': 20, 'copy_X': False, 'max_iter': 1000}",-56.448279,91
99,"{'alpha': 20, 'copy_X': False, 'max_iter': None}",-56.448279,91

In [ ]:
ridge_reg_gridcv.best_estimator_

Ridge(alpha=1, max_iter=700, random_state=42)

In [ ]:
# define ridge regression model
from sklearn.linear_model import Ridge

ridge_reg = Ridge(random_state=42, alpha=1, max_iter=700)

ridge_reg.fit(X_train, y_train)

Ridge(alpha=1, max_iter=700, random_state=42)

In [ ]:
# # define ridge regression model
# from sklearn.linear_model import Ridge

# ridge_reg = Ridge(random_state=42)

# # tune lambda (denote as 'alpha' in sklearn)
# # using GridSearchCV
# from sklearn.model_selection import GridSearchCV

# # hyperparameter values we want to tune
# parameters = {
#     'alpha': (0.000001,0.00001,0.0001,0.001,
#               0.01, 0.1, 1, 5, 10, 20),
#     'max_iter' : (700,800,900,1000, None),
#     'copy_X': (True, False)
# }

# # the tuning
# ridge_reg_gridcv = GridSearchCV(ridge_reg, parameters, cv=5,
#                                 scoring='neg_root_mean_squared_error')
# ridge_reg_gridcv.fit(X_train, y_train)

In [ ]:
# tune decision tree
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor(random_state=42)
# hyperparameter values we want to tune
# ori max_depth : None -> default
# imp max_depth : 5,10,20,30,40,50
# ori vs imp

parameters = {
    'max_depth': (5,10,20,30,40,50, None),
    'criterion' : ('squared_error','friedman_mse','absolute_error','poisson'),
    'splitter' : ('best','random'),
    'max_features' : ('sqrt', 'log2', None)
}
# the tuning
tree_reg_gridcv = GridSearchCV(tree_reg, parameters, cv=5,
                                scoring='neg_root_mean_squared_error')
tree_reg_gridcv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(random_state=42),
             param_grid={'criterion': ('squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'),
                         'max_depth': (5, 10, 20, 30, 40, 50, None),
                         'max_features': ('sqrt', 'log2', None),
                         'splitter': ('best', 'random')},
             scoring='neg_root_mean_squared_error')

In [ ]:
heart.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [ ]:
# split the data
from sklearn.model_selection import train_test_split

X = heart.drop(columns='DEATH_EVENT').to_numpy()
y = heart[['DEATH_EVENT']].to_numpy()
y = y.reshape(len(y),) # sklean formatting

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [ ]:
heart['DEATH_EVENT'].value_counts()

DEATH_EVENT
0    203
1     96
Name: count, dtype: int64

In [ ]:
# define the estimator/model
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier()

# hyperparameter tuning
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

# default 5 : atas dan bawah 5
parameters = {
    'n_neighbors': (2,3,4,5,6,7,8),
    'metric' : ('manhattan','euclidean','cosine','cityblock'),
    'weights' : ('uniform', 'distance')
}


knn_clf_gridcv = GridSearchCV(knn_clf, parameters, cv=5, scoring='recall')
knn_clf_gridcv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ('manhattan', 'euclidean', 'cosine',
                                    'cityblock'),
                         'n_neighbors': (2, 3, 4, 5, 6, 7, 8),
                         'weights': ('uniform', 'distance')},
             scoring='recall')

In [ ]:
# define the estimator/model
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier()

# hyperparameter tuning
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

# default 5 : atas dan bawah 5
parameters = {
    'criterion' : ('gini','entropy','log_loss')
}


tree_clf_gridcv = GridSearchCV(tree_clf, parameters, cv=5, scoring='f1')
tree_clf_gridcv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ('gini', 'entropy', 'log_loss')},
             scoring='f1')

In [ ]:
pd.DataFrame(tree_clf_gridcv.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001806,0.000355,0.002593,0.000665,gini,{'criterion': 'gini'},0.620690,0.521739,0.866667,0.500000,0.64,0.629819,0.130244,2
1,0.001585,0.000053,0.002133,0.000037,entropy,{'criterion': 'entropy'},0.666667,0.400000,0.785714,0.600000,0.56,0.602476,0.126889,3
2,0.001525,0.000033,0.002162,0.000166,log_loss,{'criterion': 'log_loss'},0.689655,0.461538,0.714286,0.666667,0.64,0.634429,0.089876,1

In [ ]:
# define the estimator/model
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier()
# hyperparameter tuning
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
# default 5 : atas dan bawah 5
parameters = {
    'criterion' : ('gini','entropy','log_loss')
}
tree_clf_gridcv = RandomizedSearchCV(tree_clf, parameters, cv=5, scoring='f1')
tree_clf_gridcv.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 3 is smaller than n_iter=10. Running 3 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(),
                   param_distributions={'criterion': ('gini', 'entropy',
                                                      'log_loss')},
                   scoring='f1')

In [ ]:
# the usual splitting
from sklearn.model_selection import train_test_split

X = heart.drop(columns='DEATH_EVENT').to_numpy()
y = heart[['DEATH_EVENT']].to_numpy()
y = y.reshape(len(y),)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [ ]:
# define random forest classifier model
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(random_state=42)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

# default 5 : atas dan bawah 5
parameters = {
    'criterion' : ('gini','entropy','log_loss')
}
tree_clf_gridcv = RandomizedSearchCV(tree_clf, parameters, cv=5, scoring='f1')
tree_clf_gridcv.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 3 is smaller than n_iter=10. Running 3 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(),
                   param_distributions={'criterion': ('gini', 'entropy',
                                                      'log_loss')},
                   scoring='f1')

In [ ]:
# !pip install optuna

In [ ]:
import optuna
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

# n_estimators : 100
# GS dab RS : 80,90,100,110,120
# ternyata yang terbaik adalah 105

# optuna
# min dan max : 80 - 120
# akan mencari 80 - 120, -> 81, 83, 87, 111,
# n_estimators default 100

# n_estimators = trial.suggest_int('n_estimators', 50, 150)
# 'n_estimators' : (51,52,53,53,....., 148,149,150) : 150 value

# max_depth = trial.suggest_int('max_depth', 2, 32, log=True)
# 'max_depth' : (2,3,4,....., 30,31,32) : 30 value

In [ ]:
def objective(trial):
  n_estimators = trial.suggest_int('n_estimators', 50, 150)
  max_depth = trial.suggest_int('max_depth', 2, 32, log=True)
  max_features = trial.suggest_categorical('max_features', ['sqrt', 'log2', None])

  model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth, max_features=max_features)

  scores = cross_val_score(model, X, y, cv=5, scoring='f1')

  return scores.mean()

# Buat Optuna Study
study = optuna.create_study(direction='maximize')

# Jalankan proses optimasi
study.optimize(objective, n_trials=100)

# Dapatkan hasil terbaik
best_params = study.best_params
best_value = study.best_value
print(f"Best parameters: {best_params}")
print(f"Best value: {best_value}")

[I 2025-07-26 04:21:57,960] A new study created in memory with name: no-name-c4803b7e-aea4-4ede-9b19-47614ee30569
[I 2025-07-26 04:21:59,173] Trial 0 finished with value: 0.42622818622818626 and parameters: {'n_estimators': 119, 'max_depth': 8, 'max_features': None}. Best is trial 0 with value: 0.42622818622818626.
[I 2025-07-26 04:21:59,708] Trial 1 finished with value: 0.45584116366725064 and parameters: {'n_estimators': 65, 'max_depth': 2, 'max_features': 'log2'}. Best is trial 1 with value: 0.45584116366725064.
[I 2025-07-26 04:22:00,148] Trial 2 finished with value: 0.47246246246246243 and parameters: {'n_estimators': 52, 'max_depth': 14, 'max_features': 'log2'}. Best is trial 2 with value: 0.47246246246246243.
[I 2025-07-26 04:22:01,305] Trial 3 finished with value: 0.40961409151396316 and parameters: {'n_estimators': 113, 'max_depth': 19, 'max_features': None}. Best is trial 2 with value: 0.47246246246246243.
[I 2025-07-26 04:22:01,924] Trial 4 finished with value: 0.3632135612865836 and parameters: {'n_estimators': 79, 'max_depth': 2, 'max_features': 'log2'}. Best is trial 2 with value: 0.47246246246246243.
[I 2025-07-26 04:22:02,650] Trial 5 finished with value: 0.4330533610533611 and parameters: {'n_estimators': 88, 'max_depth': 16, 'max_features': 'log2'}. Best is trial 2 with value: 0.47246246246246243.
[I 2025-07-26 04:22:03,894] Trial 6 finished with value: 0.4721174418221915 and parameters: {'n_estimators': 147, 'max_depth': 18, 'max_features': 'sqrt'}. Best is trial 2 with value: 0.47246246246246243.
[I 2025-07-26 04:22:04,863] Trial 7 finished with value: 0.47041604010025057 and parameters: {'n_estimators': 117, 'max_depth': 13, 'max_features': 'sqrt'}. Best is trial 2 with value: 0.47246246246246243.
[I 2025-07-26 04:22:05,615] Trial 8 finished with value: 0.48196248196248187 and parameters: {'n_estimators': 66, 'max_depth': 3, 'max_features': 'sqrt'}. Best is trial 8 with value: 0.48196248196248187.
[I 2025-07-26 04:22:06,467] Trial 9 finished with value: 0.4792230576441102 and parameters: {'n_estimators': 64, 'max_depth': 10, 'max_features': 'sqrt'}. Best is trial 8 with value: 0.48196248196248187.
[I 2025-07-26 04:22:07,647] Trial 10 finished with value: 0.4528595843664336 and parameters: {'n_estimators': 91, 'max_depth': 4, 'max_features': 'sqrt'}. Best is trial 8 with value: 0.48196248196248187.
[I 2025-07-26 04:22:08,536] Trial 11 finished with value: 0.45445014976465553 and parameters: {'n_estimators': 65, 'max_depth': 5, 'max_features': 'sqrt'}. Best is trial 8 with value: 0.48196248196248187.
[I 2025-07-26 04:22:09,195] Trial 12 finished with value: 0.436408457040036 and parameters: {'n_estimators': 51, 'max_depth': 8, 'max_features': 'sqrt'}. Best is trial 8 with value: 0.48196248196248187.
[I 2025-07-26 04:22:09,768] Trial 13 finished with value: 0.48715796340165485 and parameters: {'n_estimators': 71, 'max_depth': 3, 'max_features': 'sqrt'}. Best is trial 13 with value: 0.48715796340165485.
[I 2025-07-26 04:22:10,421] Trial 14 finished with value: 0.4338881775501493 and parameters: {'n_estimators': 79, 'max_depth': 3, 'max_features': 'sqrt'}. Best is trial 13 with value: 0.48715796340165485.
[I 2025-07-26 04:22:11,187] Trial 15 finished with value: 0.4792063492063493 and parameters: {'n_estimators': 100, 'max_depth': 3, 'max_features': 'sqrt'}. Best is trial 13 with value: 0.48715796340165485.
[I 2025-07-26 04:22:11,931] Trial 16 finished with value: 0.4308062015503876 and parameters: {'n_estimators': 74, 'max_depth': 5, 'max_features': None}. Best is trial 13 with value: 0.48715796340165485.
[I 2025-07-26 04:22:13,197] Trial 17 finished with value: 0.49157176725597773 and parameters: {'n_estimators': 148, 'max_depth': 28, 'max_features': 'sqrt'}. Best is trial 17 with value: 0.49157176725597773.
[I 2025-07-26 04:22:14,437] Trial 18 finished with value: 0.4526315789473684 and parameters: {'n_estimators': 146, 'max_depth': 32, 'max_features': 'sqrt'}. Best is trial 17 with value: 0.49157176725597773.
[I 2025-07-26 04:22:15,761] Trial 19 finished with value: 0.44224764299182906 and parameters: {'n_estimators': 129, 'max_depth': 32, 'max_features': None}. Best is trial 17 with value: 0.49157176725597773.
[I 2025-07-26 04:22:16,934] Trial 20 finished with value: 0.5166739926739927 and parameters: {'n_estimators': 139, 'max_depth': 24, 'max_features': 'sqrt'}. Best is trial 20 with value: 0.5166739926739927.
[I 2025-07-26 04:22:18,071] Trial 21 finished with value: 0.45327969830295417 and parameters: {'n_estimators': 130, 'max_depth': 21, 'max_features': 'sqrt'}. Best is trial 20 with value: 0.5166739926739927.
[I 2025-07-26 04:22:19,403] Trial 22 finished with value: 0.49191763191763194 and parameters: {'n_estimators': 135, 'max_depth': 25, 'max_features': 'sqrt'}. Best is trial 20 with value: 0.5166739926739927.
[I 2025-07-26 04:22:21,266] Trial 23 finished with value: 0.4761487050960735 and parameters: {'n_estimators': 137, 'max_depth': 24, 'max_features': 'sqrt'}. Best is trial 20 with value: 0.5166739926739927.
[I 2025-07-26 04:22:23,155] Trial 24 finished with value: 0.49425053176015943 and parameters: {'n_estimators': 138, 'max_depth': 25, 'max_features': 'sqrt'}. Best is trial 20 with value: 0.5166739926739927.
[I 2025-07-26 04:22:24,319] Trial 25 finished with value: 0.47229612492770395 and parameters: {'n_estimators': 137, 'max_depth': 24, 'max_features': 'sqrt'}. Best is trial 20 with value: 0.5166739926739927.
[I 2025-07-26 04:22:25,264] Trial 26 finished with value: 0.5011908148750254 and parameters: {'n_estimators': 107, 'max_depth': 12, 'max_features': 'sqrt'}. Best is trial 20 with value: 0.5166739926739927.
[I 2025-07-26 04:22:26,150] Trial 27 finished with value: 0.42807995462457704 and parameters: {'n_estimators': 103, 'max_depth': 12, 'max_features': 'sqrt'}. Best is trial 20 with value: 0.5166739926739927.
[I 2025-07-26 04:22:27,078] Trial 28 finished with value: 0.5242857142857142 and parameters: {'n_estimators': 109, 'max_depth': 10, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:28,038] Trial 29 finished with value: 0.4964957264957266 and parameters: {'n_estimators': 109, 'max_depth': 10, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:29,091] Trial 30 finished with value: 0.47403348554033486 and parameters: {'n_estimators': 126, 'max_depth': 7, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:30,024] Trial 31 finished with value: 0.49891975260396315 and parameters: {'n_estimators': 109, 'max_depth': 9, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:30,958] Trial 32 finished with value: 0.4636669636669636 and parameters: {'n_estimators': 108, 'max_depth': 10, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:31,977] Trial 33 finished with value: 0.43948346339650685 and parameters: {'n_estimators': 122, 'max_depth': 6, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:32,767] Trial 34 finished with value: 0.5188773388773389 and parameters: {'n_estimators': 93, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:33,671] Trial 35 finished with value: 0.48854992574693545 and parameters: {'n_estimators': 85, 'max_depth': 16, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:34,950] Trial 36 finished with value: 0.48877763514477257 and parameters: {'n_estimators': 96, 'max_depth': 12, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:36,414] Trial 37 finished with value: 0.4295659269508453 and parameters: {'n_estimators': 94, 'max_depth': 15, 'max_features': None}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:37,626] Trial 38 finished with value: 0.475490264121843 and parameters: {'n_estimators': 116, 'max_depth': 20, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:38,488] Trial 39 finished with value: 0.46136071887034663 and parameters: {'n_estimators': 103, 'max_depth': 17, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:39,335] Trial 40 finished with value: 0.41273602611179105 and parameters: {'n_estimators': 82, 'max_depth': 13, 'max_features': None}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:40,243] Trial 41 finished with value: 0.45734215997373884 and parameters: {'n_estimators': 110, 'max_depth': 8, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:41,264] Trial 42 finished with value: 0.4706666666666666 and parameters: {'n_estimators': 123, 'max_depth': 9, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:42,214] Trial 43 finished with value: 0.4864271790587581 and parameters: {'n_estimators': 114, 'max_depth': 11, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:43,098] Trial 44 finished with value: 0.48807343941248477 and parameters: {'n_estimators': 105, 'max_depth': 14, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:43,855] Trial 45 finished with value: 0.4867724245985115 and parameters: {'n_estimators': 92, 'max_depth': 7, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:44,681] Trial 46 finished with value: 0.44811006879299564 and parameters: {'n_estimators': 99, 'max_depth': 19, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:45,436] Trial 47 finished with value: 0.4785128205128205 and parameters: {'n_estimators': 88, 'max_depth': 9, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:46,422] Trial 48 finished with value: 0.44790648772342134 and parameters: {'n_estimators': 120, 'max_depth': 6, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:47,913] Trial 49 finished with value: 0.4148062015503876 and parameters: {'n_estimators': 114, 'max_depth': 14, 'max_features': None}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:49,789] Trial 50 finished with value: 0.4803143829237232 and parameters: {'n_estimators': 144, 'max_depth': 9, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:51,177] Trial 51 finished with value: 0.45380369843527746 and parameters: {'n_estimators': 108, 'max_depth': 11, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:52,102] Trial 52 finished with value: 0.45544144144144144 and parameters: {'n_estimators': 111, 'max_depth': 10, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:52,936] Trial 53 finished with value: 0.46905336105336104 and parameters: {'n_estimators': 99, 'max_depth': 8, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:53,848] Trial 54 finished with value: 0.4828686492357866 and parameters: {'n_estimators': 107, 'max_depth': 12, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:54,825] Trial 55 finished with value: 0.4451201766270259 and parameters: {'n_estimators': 118, 'max_depth': 6, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:55,660] Trial 56 finished with value: 0.4734026334026334 and parameters: {'n_estimators': 98, 'max_depth': 17, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:56,502] Trial 57 finished with value: 0.4966416040100251 and parameters: {'n_estimators': 102, 'max_depth': 11, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:57,127] Trial 58 finished with value: 0.45810810810810815 and parameters: {'n_estimators': 60, 'max_depth': 13, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:58,256] Trial 59 finished with value: 0.5182668382668383 and parameters: {'n_estimators': 90, 'max_depth': 15, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:22:59,407] Trial 60 finished with value: 0.4411721194879089 and parameters: {'n_estimators': 75, 'max_depth': 21, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:00,336] Trial 61 finished with value: 0.4887151337383896 and parameters: {'n_estimators': 88, 'max_depth': 15, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:02,412] Trial 62 finished with value: 0.46414203836626944 and parameters: {'n_estimators': 95, 'max_depth': 11, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:03,636] Trial 63 finished with value: 0.4665525525525525 and parameters: {'n_estimators': 90, 'max_depth': 29, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:05,027] Trial 64 finished with value: 0.4533934420250209 and parameters: {'n_estimators': 103, 'max_depth': 18, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:05,996] Trial 65 finished with value: 0.5031331915180897 and parameters: {'n_estimators': 81, 'max_depth': 22, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:07,183] Trial 66 finished with value: 0.47772793629019566 and parameters: {'n_estimators': 81, 'max_depth': 22, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:07,785] Trial 67 finished with value: 0.48322102590395277 and parameters: {'n_estimators': 70, 'max_depth': 29, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:08,471] Trial 68 finished with value: 0.46886951295253754 and parameters: {'n_estimators': 77, 'max_depth': 26, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:09,364] Trial 69 finished with value: 0.49705802968960866 and parameters: {'n_estimators': 55, 'max_depth': 23, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:10,213] Trial 70 finished with value: 0.4185714285714286 and parameters: {'n_estimators': 84, 'max_depth': 15, 'max_features': None}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:11,387] Trial 71 finished with value: 0.4887268170426065 and parameters: {'n_estimators': 132, 'max_depth': 23, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:12,254] Trial 72 finished with value: 0.49963369963369964 and parameters: {'n_estimators': 62, 'max_depth': 19, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:13,249] Trial 73 finished with value: 0.47983738658157266 and parameters: {'n_estimators': 92, 'max_depth': 16, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:13,994] Trial 74 finished with value: 0.4807288491499017 and parameters: {'n_estimators': 68, 'max_depth': 19, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:14,686] Trial 75 finished with value: 0.464981684981685 and parameters: {'n_estimators': 59, 'max_depth': 18, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:15,948] Trial 76 finished with value: 0.48327144120247567 and parameters: {'n_estimators': 85, 'max_depth': 27, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:18,368] Trial 77 finished with value: 0.4553730480046269 and parameters: {'n_estimators': 141, 'max_depth': 13, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:19,607] Trial 78 finished with value: 0.47592592592592586 and parameters: {'n_estimators': 73, 'max_depth': 20, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:20,360] Trial 79 finished with value: 0.4053245660687521 and parameters: {'n_estimators': 50, 'max_depth': 14, 'max_features': None}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:21,443] Trial 80 finished with value: 0.4835890410958904 and parameters: {'n_estimators': 96, 'max_depth': 16, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:22,054] Trial 81 finished with value: 0.49552026749223305 and parameters: {'n_estimators': 57, 'max_depth': 23, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:22,679] Trial 82 finished with value: 0.4632363132363132 and parameters: {'n_estimators': 63, 'max_depth': 21, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:23,262] Trial 83 finished with value: 0.47942732029688545 and parameters: {'n_estimators': 53, 'max_depth': 31, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:23,887] Trial 84 finished with value: 0.4785764149613131 and parameters: {'n_estimators': 55, 'max_depth': 9, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:24,542] Trial 85 finished with value: 0.4676556776556776 and parameters: {'n_estimators': 64, 'max_depth': 17, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:25,354] Trial 86 finished with value: 0.3778266303948239 and parameters: {'n_estimators': 105, 'max_depth': 2, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:26,284] Trial 87 finished with value: 0.4615740901363495 and parameters: {'n_estimators': 112, 'max_depth': 24, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:26,953] Trial 88 finished with value: 0.47637878479983753 and parameters: {'n_estimators': 79, 'max_depth': 12, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:28,024] Trial 89 finished with value: 0.4460490657538155 and parameters: {'n_estimators': 126, 'max_depth': 20, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:28,571] Trial 90 finished with value: 0.45863577863577865 and parameters: {'n_estimators': 62, 'max_depth': 10, 'max_features': 'log2'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:29,436] Trial 91 finished with value: 0.472051282051282 and parameters: {'n_estimators': 102, 'max_depth': 11, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:30,790] Trial 92 finished with value: 0.496690675638044 and parameters: {'n_estimators': 101, 'max_depth': 13, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:32,194] Trial 93 finished with value: 0.43294832478289524 and parameters: {'n_estimators': 106, 'max_depth': 14, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:33,614] Trial 94 finished with value: 0.47085200179937026 and parameters: {'n_estimators': 115, 'max_depth': 13, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.
[I 2025-07-26 04:23:34,354] Trial 95 finished with value: 0.4820920920920921 and parameters: {'n_estimators': 89, 'max_depth': 18, 'max_features': 'sqrt'}. Best is trial 28 with value: 0.5242857142857142.

Best parameters: {'n_estimators': 109, 'max_depth': 10, 'max_features': 'log2'}
Best value: 0.5242857142857142