## Import Package

In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from imblearn.over_sampling import SMOTE

from sklearn import preprocessing
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix

## Load dataset

dataset -> https://www.kaggle.com/datasets/parisrohan/credit-score-classification

In [2]:
df = pd.read_csv('sample_data/train.csv')
map_cs = {
    'Poor' : 1,
    'Standard':0,
    'Good': 0
}
df['Credit_Score'] = df['Credit_Score'].map(map_cs)

data_numeric = df.select_dtypes(include=np.number)
data_numeric = data_numeric.dropna().reset_index(drop=True)
data_numeric.head()

,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Delay_from_due_date,Num_Credit_Inquiries,Credit_Utilization_Ratio,Total_EMI_per_month,Credit_Score
0,1824.843333,3.0,4.0,3.0,3.0,4.0,26.822620,49.574949,0.0
1,1824.843333,3.0,4.0,3.0,6.0,4.0,24.797347,49.574949,0.0
2,1824.843333,3.0,4.0,3.0,3.0,4.0,22.537593,49.574949,0.0
3,1824.843333,3.0,4.0,3.0,3.0,4.0,23.933795,49.574949,0.0
4,3037.986667,2.0,4.0,6.0,3.0,2.0,24.464031,18.816215,0.0

In [3]:
data_numeric['Credit_Score'].value_counts()

Credit_Score
0.0    3983
1.0    1665
Name: count, dtype: int64

In [4]:
data_numeric['Credit_Score'].value_counts(normalize=True)

Credit_Score
0.0    0.705205
1.0    0.294795
Name: proportion, dtype: float64

## Split between feature and target

In [5]:
# fitur
X = data_numeric.drop(['Credit_Score'],axis=1)
# target
y = data_numeric['Credit_Score']

## Split data -> train, val, test

In [19]:
X_pretrain, X_test, y_pretrain, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# X_test -> data original -> test

In [9]:
from imblearn import over_sampling

# Overampling with smote
X_over_smote, y_over_smote = over_sampling.SMOTE().fit_resample(X_pretrain, y_pretrain)

In [13]:
X_train, X_val, y_train, y_val = train_test_split(X_over_smote, y_over_smote, test_size=0.2, random_state=42)

## Modeling

In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_auc_score, classification_report, f1_score

In [14]:
# model = DecisionTreeClassifier()
model = RandomForestClassifier(n_estimators=100)
model.fit(X_train,y_train)
y_pred = model.predict(X_val)

## Evaluation

In [15]:
print(classification_report(y_val, y_pred, digits=6))

              precision    recall  f1-score   support

         0.0   0.905844  0.882911  0.894231       632
         1.0   0.888048  0.910078  0.898928       645

    accuracy                       0.896633      1277
   macro avg   0.896946  0.896494  0.896579      1277
weighted avg   0.896856  0.896633  0.896603      1277

In [20]:
y_pred_test = model.predict(X_test)
print(classification_report(y_test, y_pred_test, digits=6))

              precision    recall  f1-score   support

         0.0   0.913333  0.864899  0.888457       792
         1.0   0.718421  0.807692  0.760446       338

    accuracy                       0.847788      1130
   macro avg   0.815877  0.836296  0.824451      1130
weighted avg   0.855032  0.847788  0.850167      1130

In [ ]:
# from sklearn.metrics import precision_score
# precision_score(y_val, y_pred)

In [ ]:
# from sklearn.metrics import recall_score
# recall_score(y_val, y_pred)

In [ ]:
# from sklearn.metrics import f1_score
# f1_score(y_val, y_pred, average='weighted')

## Contoh mencari point baru pada SMOTE

In [ ]:
import numpy as np

def find_new_point(minority_sample, neighbor, random_factor):
    # Hitung vektor jarak antara sampel minoritas dan tetangga
    distance_vector = neighbor - minority_sample

    # Interpolasi linear dengan mengalikan vektor jarak dengan faktor acak
    new_point = minority_sample + random_factor * distance_vector

    return new_point

# Contoh penggunaan fungsi
minority_sample = np.array([0.2, 0.3, 0.4])  # Contoh sampel minoritas
neighbor = np.array([0.25, 0.35, 0.45])  # Contoh tetangga terdekat
random_factor = 0.5  # Faktor acak

new_point = find_new_point(minority_sample, neighbor, random_factor)
print("Koordinat titik baru:", new_point)

Koordinat titik baru: [0.225 0.325 0.425]